/*****************************************************************************************
The SAS data set called CATS contains information about breeds of cats. The variables are the name
of the breed, the place where the breed originated, how the breed was derived, the type of hair,
and a description of the breed’s appearance. The following program produces counts of breed by
place of origin, and then prints a report listing all the data for breeds that originated in Thailand.
Modify the program using macro variables and a macro to increase its flexibility.
LIBNAME sasdata 'c:\MySASLib';
** Original code without macro variables;
PROC FREQ DATA = sasdata.cats;
TABLES Origin;
TITLE 'Cat Breeds by Origin';
RUN;
PROC PRINT DATA = sasdata.cats;
WHERE Origin = 'Thailand';
TITLE 'Cat Breeds with Origin = Thailand';
RUN;
a. Examine this SAS data set including the variable labels and attributes. Use %LET statements to
create two macro variables: one to replace the variable name Origin, and another to replace the
data value 'Thailand'. Use an option that will enable you to see the standard SAS statements
generated by the macro processor.
b. Use the macro variables to produce counts for the variable Derivation, and to list data for
breeds that were derived by mutation.
c. Convert the code to a macro. Pass the values for the two macro variables into the macro as
parameters. Call the macro to produce counts for the variable Hair, and to list data for breeds
with long hair.
d. Add programming to your macro from part c) that will save your output in a PDF file. Name
this file CatRpt, and append the filename with a suffix that is the name of the variable used in
the TABLES statement.

******************************************************************************************/


libname practice "/folders/myfolders/sasuser.v94";

proc contents data = practice.cats varnum;
run;

%LET Var=Origin;
%LET Val=Thailand;

PROC FREQ data = practice.cats;
	TABLES &Var.;
	TITLE "Cat Breeds by Origin";
RUN;

PROC PRINT DATA = practice.cats;
WHERE &Var. = "&Val.";
TITLE 'Cat Breeds with &Var. = &Val.';
RUN;

%LET Var2=Derivation;
%LET Val2=Mutation;

PROC FREQ DATA = practice.cats;
TABLES &Var2.;
RUN;

PROC PRINT DATA = practice.cats;
WHERE &Var2. = "&Val2.";
TITLE "Cat Breeds by &Var2.";
RUN;

%macro cats (V1,V2);
PROC FREQ data = practice.cats;
	TABLES &V1.;
	TITLE "Cat Breeds by &V1.";
RUN;

PROC PRINT DATA = practice.cats;
WHERE &V1. = "&V2.";
Title "Cat Breeds with &V1.=&V2.";
RUN;

%mend cats;
%cats(Origin,Thailand)
%cats(Hair,Hair type)